apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: "opinion_bot"
    user: "postgres"
    secureJsonData:
      password: "12345"
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: false
