stream {
    upstream postgres {
        server db:5432;
    }

    server {
#        listen 5432; TODO: revert when 5432 is open
        listen 80;
        ssl on;
        ssl_certificate /etc/db_access_certs/server.crt;
        ssl_certificate_key /etc/db_access_certs/server.key;
        ssl_client_certificate /etc/db_access_certs/ca.crt;
        ssl_verify_client on;
        ssl_verify_depth 1;
        proxy_pass postgres;
    }
}
