local   all             all                                     trust
hostnossl all           all             samenet                 scram-sha-256
hostssl all             all             0.0.0.0/0               scram-sha-256 clientcert=verify-ca
hostnossl all           all             0.0.0.0/0               reject
