listen_addresses = '*'
ssl = on
ssl_ca_file = '/etc/postgresql/db_access_certs/ca.crt'
ssl_cert_file = '/etc/postgresql/db_access_certs/server.crt'
ssl_key_file = '/etc/postgresql/db_access_certs/server.key'
hba_file = '/etc/postgresql/pg_hba.conf'
password_encryption = scram-sha-256
