# Generated by Django 4.2.28 on 2026-02-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(help_text="Discord channel snowflake ID", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, help_text="Channel name (for admin display)", max_length=255)),
                (
                    "netuid",
                    models.PositiveIntegerField(db_index=True, help_text="Subnet netuid this channel is mapped to"),
                ),
                (
                    "is_archived",
                    models.BooleanField(db_index=True, default=False, help_text="Archived channels hidden by default"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discord Channel",
                "verbose_name_plural": "Discord Channels",
            },
        ),
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                (
                    "id",
                    models.BigIntegerField(help_text="Discord role snowflake ID", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(help_text="Role name from Discord", max_length=255)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier for API filtering", max_length=64, unique=True),
                ),
                (
                    "is_key_role",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Key roles used in queries (subnet_owner, validator, founder, etc.)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discord Role",
                "verbose_name_plural": "Discord Roles",
            },
        ),
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(help_text="Discord user snowflake ID", primary_key=True, serialize=False),
                ),
                ("username", models.CharField(help_text="Global Discord username", max_length=255)),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Per-guild display name (nick), may differ from username", max_length=255
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discord User",
                "verbose_name_plural": "Discord Users",
            },
        ),
        migrations.CreateModel(
            name="SubnetInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("netuid", models.PositiveIntegerField(db_index=True)),
                ("name", models.CharField(blank=True, help_text="Human-readable subnet name", max_length=100)),
                (
                    "registration_block",
                    models.PositiveBigIntegerField(help_text="Block number when this subnet was registered"),
                ),
                (
                    "deregistration_block",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Block number when deregistered (null = still active)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subnet Instance",
                "verbose_name_plural": "Subnet Instances",
                "unique_together": {("netuid", "registration_block")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="opinion_bot.discordrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="opinion_bot.discorduser",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "unique_together": {("user", "role")},
            },
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(help_text="Emoji representing the opinion sentiment", max_length=64)),
                ("content", models.TextField(help_text="The opinion text content")),
                (
                    "source_message_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, help_text="Original Discord message ID", null=True
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("featured", "Featured"), ("hidden", "Hidden"), ("archived", "Archived")],
                        db_index=True,
                        default="hidden",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who submitted the opinion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_opinions",
                        to="opinion_bot.discorduser",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to="opinion_bot.discordchannel",
                    ),
                ),
                (
                    "subnet_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to="opinion_bot.subnetinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opinion",
                "verbose_name_plural": "Opinions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["visibility", "created_at"], name="opinion_bot_visibil_5938da_idx"),
                    models.Index(fields=["subnet_instance", "visibility"], name="opinion_bot_subnet__9069d7_idx"),
                    models.Index(fields=["author", "created_at"], name="opinion_bot_author__086360_idx"),
                ],
            },
        ),
    ]
