# Generated by Django 4.2.28 on 2026-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_bot', '0002_remove_opinion_opinion_bot_subnet__9069d7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='message_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Discord message ID', null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('replaced', 'Replaced')], default='pending', max_length=16),
        ),
    ]
