# Generated by Django 4.2.28 on 2026-02-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_bot', '0003_alter_opinion_message_id_alter_opinion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('featured', 'Featured'), ('hidden', 'Hidden')], db_index=True, default='hidden', max_length=16)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('replaced', 'Replaced')], default='valid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Upvote',
                'verbose_name_plural': 'Upvotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='opinion',
            name='opinion_bot_visibil_5938da_idx',
        ),
        migrations.RemoveIndex(
            model_name='opinion',
            name='opinion_bot_author__086360_idx',
        ),
        migrations.RemoveIndex(
            model_name='opinion',
            name='opinion_bot_channel_f40290_idx',
        ),
        migrations.AddIndex(
            model_name='opinion',
            index=models.Index(fields=['channel', 'visibility', 'status', 'created_at'], name='opinion_bot_channel_b65770_idx'),
        ),
        migrations.AddIndex(
            model_name='opinion',
            index=models.Index(fields=['channel', 'author', 'status', 'created_at'], name='opinion_bot_channel_b0d154_idx'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='author',
            field=models.ForeignKey(help_text='User who upvoted the opinion', on_delete=django.db.models.deletion.CASCADE, related_name='authored_upvotes', to='opinion_bot.discorduser'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='opinion_bot.discordchannel'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='opinion',
            field=models.ForeignKey(help_text='Upvoted opinion', on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_opinions', to='opinion_bot.opinion'),
        ),
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['channel', 'visibility', 'status', 'created_at'], name='opinion_bot_channel_4cd811_idx'),
        ),
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['channel', 'author', 'status'], name='opinion_bot_channel_ef21ae_idx'),
        ),
    ]
