# Generated by Django 4.2.28 on 2026-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opinion_bot", "0004_upvote_remove_opinion_opinion_bot_visibil_5938da_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="opinion",
            index=models.Index(fields=["message_id"], name="opinion_bot_message_58a0a8_idx"),
        ),
    ]
