# Generated by Django 4.2.28 on 2026-02-23 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opinion_bot", "0005_opinion_opinion_bot_message_58a0a8_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="opinions", to="opinion_bot.discordchannel"
            ),
        ),
        migrations.AlterField(
            model_name="upvote",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="upvotes", to="opinion_bot.discordchannel"
            ),
        ),
        migrations.AlterField(
            model_name="upvote",
            name="opinion",
            field=models.ForeignKey(
                help_text="Upvoted opinion",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="upvoted_opinions",
                to="opinion_bot.opinion",
            ),
        ),
    ]
