# Generated by Django 4.2.28 on 2026-03-17 19:13

from django.db import migrations


def delete_opinions_and_upvotes(apps, schema_editor):
    Opinion = apps.get_model("opinion_bot", "Opinion")
    Upvote = apps.get_model("opinion_bot", "Upvote")
    Upvote.objects.all().delete()
    Opinion.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("opinion_bot", "0006_alter_opinion_channel_alter_upvote_channel_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_opinions_and_upvotes, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="SubnetInstance",
        ),
    ]
