# Generated by Django 4.2.28 on 2026-03-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("opinion_bot", "0007_delete_subnetinstance"),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM opinion_bot_upvote;"),
        migrations.RunSQL("DELETE FROM opinion_bot_opinion;"),
        migrations.RunSQL("DELETE FROM opinion_bot_discordchannel;"),
        migrations.CreateModel(
            name="SubnetInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, help_text="Channel name (for admin display)", max_length=255)),
                (
                    "netuid",
                    models.PositiveIntegerField(db_index=True, help_text="Subnet netuid this channel is mapped to"),
                ),
                (
                    "is_archived",
                    models.BooleanField(db_index=True, default=False, help_text="Archived channels hidden by default"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subnet Instance",
                "verbose_name_plural": "Subnet Instances",
            },
        ),
        migrations.RemoveIndex(
            model_name="opinion",
            name="opinion_bot_channel_b65770_idx",
        ),
        migrations.RemoveIndex(
            model_name="opinion",
            name="opinion_bot_channel_b0d154_idx",
        ),
        migrations.RemoveIndex(
            model_name="upvote",
            name="opinion_bot_channel_4cd811_idx",
        ),
        migrations.RemoveIndex(
            model_name="upvote",
            name="opinion_bot_channel_ef21ae_idx",
        ),
        migrations.RemoveField(
            model_name="opinion",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="upvote",
            name="channel",
        ),
        migrations.DeleteModel(
            name="DiscordChannel",
        ),
        migrations.AddField(
            model_name="opinion",
            name="subnet_instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="opinions",
                to="opinion_bot.subnetinstance",
            ),
        ),
        migrations.AddField(
            model_name="upvote",
            name="subnet_instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="upvotes",
                to="opinion_bot.subnetinstance",
            ),
        ),
        migrations.AddIndex(
            model_name="opinion",
            index=models.Index(
                fields=["subnet_instance", "visibility", "status", "created_at"], name="opinion_bot_subnet__6ea8fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opinion",
            index=models.Index(
                fields=["subnet_instance", "author", "status", "created_at"], name="opinion_bot_subnet__252443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upvote",
            index=models.Index(
                fields=["subnet_instance", "visibility", "status", "created_at"], name="opinion_bot_subnet__df0a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upvote",
            index=models.Index(fields=["subnet_instance", "author", "status"], name="opinion_bot_subnet__004f67_idx"),
        ),
    ]
