# Generated by Django 4.2.28 on 2026-03-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opinion_bot", "0008_subnetinstance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="subnet_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="opinions", to="opinion_bot.subnetinstance"
            ),
        ),
        migrations.AlterField(
            model_name="upvote",
            name="subnet_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="upvotes", to="opinion_bot.subnetinstance"
            ),
        ),
    ]
