# Generated by Django 4.2.28 on 2026-03-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opinion_bot", "0009_alter_opinion_subnet_instance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnetinstance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subnetinstance",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="subnetinstance",
            name="name",
            field=models.CharField(blank=True, help_text="Human readable subnet instance name", max_length=255),
        ),
        migrations.AlterField(
            model_name="subnetinstance",
            name="netuid",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name="subnetinstance",
            index=models.Index(fields=["is_archived", "netuid"], name="opinion_bot_is_arch_dc21cd_idx"),
        ),
    ]
