# Generated by Django 4.2.28 on 2026-03-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opinion_bot", "0010_alter_subnetinstance_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnetinstance",
            name="name",
            field=models.CharField(help_text="Human readable subnet instance name", max_length=255),
        ),
    ]
