# Generated by Django 4.2.28 on 2026-05-04 11:52

from django.db import migrations
from django.contrib.contenttypes.management import create_contenttypes
from django.apps import apps as global_apps


def create_moderators_group(apps, schema_editor):
    # ensure content types exist
    for app_config in global_apps.get_app_configs():
        create_contenttypes(app_config)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    group, _ = Group.objects.get_or_create(name="Moderators")

    permissions = []
    for model_name in ("discordrole", "subnetinstance"):
        content_type = ContentType.objects.get(app_label="opinion_bot", model=model_name)
        permissions.extend(
            Permission.objects.filter(
                content_type=content_type,
                codename__in=(
                    f"add_{model_name}",
                    f"change_{model_name}",
                    f"delete_{model_name}",
                    f"view_{model_name}",
                ),
            )
        )

    group.permissions.set(permissions)


def remove_moderators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Moderators").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ('opinion_bot', '0012_readonly_role_permissions'),
    ]

    operations = [
        migrations.RunPython(create_moderators_group, reverse_code=remove_moderators_group),
    ]
